# Project Information
site_name: PagerDuty DevSecOps Documentation
site_description: This guide is an introduction to DevSecOps, the cultural practice of integrating the security team into the process flow of development and operations.
site_author: PagerDuty, Inc.
site_url: https://devsecops.pagerduty.com/

# Repository
repo_url: https://github.com/PagerDuty/devsecops-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'DevSecOps'

# Contents
nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Security Terminology: 'terminology.md'
  - Cultural Changes:
    - Building Empathy: 'culture/building_empathy.md'
    - Team Interactions: 'culture/team_interactions.md'
  - Implementation:
    - Shift Security Left: 'implement/shift_left.md'
    - Training and Education: 'implement/training.md'
  - Additional Information:
    - Secure SDLC: 'secure_sdlc.md'
    - Resources and References: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'

