# Project Information
site_name: PagerDuty DevSecOps Documentation
site_description: This is a description of this guide.
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: 'https://devsecops.pagerduty.com'

# Repository
repo_url: https://github.com/PagerDuty/devsecops-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra_javascript: ['js/github_forks.js']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/covers/default.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Dev URL
dev_addr: '0.0.0.0:8080'

# Contents
##FIXME : Add additional pages below the index and introduction, as needed
##Format should be:
##      Name of Page: 'filename.md'
## Or:
##      Name of Parent Topic:
##        Name of Subtopic: 'path/filename.md'
pages:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Security Terminology: 'terminology.md'
  - Cultural Changes: 
    - Building Empathy: 'culture/building_empathy.md'
    - Team Interactions: 'culture/team_interactions.md'
  - Implementation:
    - Shift Security Left: 'implement/shift_left.md'
    - Training and Education: 'implement/training.md'
  - Additional Information:
    - Secure SDLC: 'secure_sdlc.md'
    - Resources and References: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
